services:
  ClickSolutions\ContaoLoginScreenBundle\EventListener\Hooks\ParseTemplateListener:
    arguments:
      - '%kernel.project_dir%'
      - '@contao.image.studio'
    tags:
      - { name: contao.hook, hook: parseTemplate }
